openapi: 3.0.2
info:
  description: University of Arizona Concept Alignment API
  title: linking
  version: 1.0.0
servers:
  - url: http://localhost:9002
    description: Local host running the jclapp

components:
  schemas:
    status:
      type: array
      items:
        type: object
        properties:
          score:
            description: a value in the range [-1, 1] with higher being a better match for the search
            type: number
            format: float
          datamartId:
            description: an indication of the source of the data to distinguish clashing datasetIds from different sources.  Together the datamartId, datasetId, and variableId should form a GUID.
            type: string
          datasetId:
            description: a unique identifer for the dataset of a particular datamart
            type: string
          variableId:
            description: a unique identifier for a variable of a particular dataset
            type: string
          variableName:
            description: a more human readable version of the variableId
            type: string
          variableDescription:
            description: an more thorough explanation of the variable
            type: string
            
paths:
  /v1/ping:
    get:
      summary: Respond with OK
      responses:
        200:
          description: OK

  /v1/echo:
    get:
      summary: Echo back the input text
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A copy of the input
          content:
            'text/plain; charset=utf-8':
              schema:
                type: string

  /v1/status:
    get:
      summary: Retrieve the current status of both job controller and the concept aligner
      description: "The query term is converted to vectors, the nearest matches from the datamart are found, and then they are returned with descriptions."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
  /v1/start:
    get:
      summary: Start the concept aligner
      description: "The query term is converted to vectors, the nearest matches from the datamart are found, and then they are returned with descriptions."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
  /v1/stop:
    get:
      summary: Stop the concept aligner
      description: "The query term is converted to vectors, the nearest matches from the datamart are found, and then they are returned with descriptions."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
  /v1/index:
    get:
      summary: Scrape and reindex the datamarts and SuperMaaS // allow parameters so know url of supermaas server
      description: "The query term is converted to vectors, the nearest matches from the datamart are found, and then they are returned with descriptions."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
